import { getFirestore, Timestamp } from 'firebase-admin/firestore';

/**
 * One set of tips per city, for everyone.
 *
 * The tips for Lisbon are the same whoever asks, so the first answer is kept
 * in `city_tips/{country_city}` and served from there to every later caller,
 * on every phone, without a model call and without touching their daily
 * budget. A cached entry is good for `TTL_DAYS`; after that the next caller
 * regenerates it, so a closed café does not stay recommended forever.
 *
 * Only the Functions write here (Admin SDK); the rules close the collection
 * to clients, like `ai_usage`.
 */

export const TTL_DAYS = 90;

/** "Ho Chi Minh City", "Viet Nam" and "ho chi minh city, vietnam" land on the same entry. */
export function tipsKey(city: string, country: string): string {
  const slug = (s: string) =>
    s
      .normalize('NFKD')
      .replace(/[̀-ͯ]/g, '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '')
      .slice(0, 60) || 'unknown';
  return `${slug(country)}__${slug(city)}`;
}

export interface CachedTips {
  tips: string;
  /** Freshly generated by this call, rather than read back. */
  generated: boolean;
}

/**
 * The tips for a city: from the cache when it has them and they are not
 * stale, otherwise from `generate`, which runs at most once per city per
 * `TTL_DAYS`. `generate` is where the quota is spent, so a cache hit is free
 * for the caller.
 */
export async function cachedCityTips(
  city: string,
  country: string,
  generate: () => Promise<string>,
  now: Date = new Date(),
): Promise<CachedTips> {
  const ref = getFirestore().collection('city_tips').doc(tipsKey(city, country));
  const snap = await ref.get();
  const data = snap.exists ? snap.data() : undefined;
  const expires = data?.expiresAt instanceof Timestamp ? data.expiresAt.toDate() : null;
  if (typeof data?.tips === 'string' && data.tips && expires && expires > now) {
    return { tips: data.tips, generated: false };
  }

  const tips = await generate();
  const expiresAt = new Date(now);
  expiresAt.setDate(expiresAt.getDate() + TTL_DAYS);
  await ref.set({
    city,
    country,
    tips,
    createdAt: Timestamp.fromDate(now),
    // Set a Firestore TTL policy on this field (collection `city_tips`,
    // field `expiresAt`) and stale entries delete themselves; until then
    // the date check above does the same job.
    expiresAt: Timestamp.fromDate(expiresAt),
  });
  return { tips, generated: true };
}
