import { LegalLayout, Section, P, UL, CONTACT_EMAIL, EFFECTIVE_DATE, APP_NAME, COMPANY, WEBSITE } from "../legal-shared";

export const metadata = {
  title: "Terms of Service – Nomady",
  description: "Terms and conditions for using the Nomady app.",
};

export default function TermsOfService() {
  return (
    <LegalLayout
      title="Terms of Service"
      subtitle={`Effective date: ${EFFECTIVE_DATE}. Please read these terms carefully before using ${APP_NAME}.`}
    >
      <Section title="1. Acceptance of Terms">
        <P>
          By downloading, installing, or using the {APP_NAME} mobile application ("App"), you
          agree to be bound by these Terms of Service ("Terms") and our{" "}
          <a href="/privacy" style={{ color: "#B8860B" }}>Privacy Policy</a>. If you do not
          agree, do not use the App.
        </P>
        <P>
          The App is operated by {COMPANY}, a US limited liability company ("we", "us", "our").
        </P>
      </Section>

      <Section title="2. Eligibility">
        <UL
          items={[
            "You must be at least 13 years old to use the App.",
            "You must have the legal capacity to enter into a binding agreement.",
            "By using the App, you represent that you meet these requirements.",
          ]}
        />
      </Section>

      <Section title="3. License">
        <P>
          We grant you a limited, non-exclusive, non-transferable, revocable license to use the
          App for your personal, non-commercial purposes, subject to these Terms.
        </P>
        <P>You may not:</P>
        <UL
          items={[
            "Copy, modify, distribute, or create derivative works of the App.",
            "Reverse engineer, decompile, or disassemble the App.",
            "Use the App to build a competing product or service.",
            "Scrape, crawl, or extract data from the App by automated means.",
            "Use the App in any way that violates applicable laws or regulations.",
          ]}
        />
      </Section>

      <Section title="4. Subscriptions & Payments">
        <P>
          {APP_NAME} offers auto-renewing subscriptions that unlock premium features ("Pro").
          Subscriptions are processed by Apple's App Store on our behalf.
        </P>
        <UL
          items={[
            "Subscription fees are charged to your Apple ID account at confirmation of purchase.",
            "Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period.",
            "You can manage or cancel your subscription in iOS Settings → Apple ID → Subscriptions.",
            "Refunds are handled by Apple in accordance with their refund policy. We have no ability to issue refunds directly.",
            "Free trial periods, if offered, will automatically convert to a paid subscription unless cancelled before the trial ends.",
            "Prices may change with reasonable notice. You will be informed of price changes via the App Store before they take effect.",
          ]}
        />
      </Section>

      <Section title="5. User Content & Data">
        <P>
          You retain ownership of all trip data, notes, and other content you create in the App
          ("Your Content"). By enabling Cloud Sync, you grant us a limited license to store and
          transmit Your Content solely to provide the sync service.
        </P>
        <P>
          You are responsible for the accuracy of data you enter. The visa and tax calculations
          the App provides are estimates based on publicly known rules and the data you input —
          they are not legal advice. See Section 8.
        </P>
      </Section>

      <Section title="6. Acceptable Use">
        <P>You agree not to use the App to:</P>
        <UL
          items={[
            "Violate any applicable law or regulation.",
            "Infringe the intellectual property rights of others.",
            "Transmit malware, spam, or any harmful code.",
            "Attempt to gain unauthorized access to our systems or other users' accounts.",
            "Engage in any activity that could damage, disable, or impair the App.",
          ]}
        />
      </Section>

      <Section title="7. AI-Generated Suggestions">
        <P>
          The App includes AI-powered destination suggestions generated by Google Gemini. These
          suggestions are provided for informational purposes only. They may be inaccurate,
          incomplete, or outdated. We do not warrant the accuracy of any AI-generated content.
          Always verify travel, visa, and entry requirements with official sources.
        </P>
      </Section>

      <Section title="8. Visa & Tax Information — Not Legal Advice">
        <P>
          The visa tracker and tax residence tracker features provide estimates based on
          generally published rules and the travel data you enter. This information:
        </P>
        <UL
          items={[
            "Is not legal or tax advice.",
            "May be inaccurate, incomplete, or out of date.",
            "Does not account for your specific circumstances.",
            "Should not be relied upon as the sole basis for any immigration or tax decision.",
          ]}
        />
        <P>
          Always consult a qualified immigration lawyer or tax professional before making
          decisions based on visa or tax residence calculations.
        </P>
      </Section>

      <Section title="9. Third-Party Services">
        <P>
          The App integrates with third-party services including Google Firebase, RevenueCat, and
          the Google Gemini API. Your use of these services is subject to their respective terms
          and privacy policies. We are not responsible for the practices of these services.
        </P>
      </Section>

      <Section title="10. Intellectual Property">
        <P>
          The App, including its design, code, trademarks, and content, is owned by {COMPANY}
          and protected by copyright and other intellectual property laws. Nothing in these Terms
          grants you any right, title, or interest in our intellectual property.
        </P>
      </Section>

      <Section title="11. Disclaimer of Warranties">
        <P>
          THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS
          OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
          PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE APP WILL BE
          UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
        </P>
      </Section>

      <Section title="12. Limitation of Liability">
        <P>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, {COMPANY.toUpperCase()} AND ITS MEMBERS,
          OFFICERS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
          SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF
          PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE APP,
          EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        </P>
        <P>
          OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM THESE TERMS OR YOUR USE OF THE
          APP SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM,
          OR $100 USD, WHICHEVER IS GREATER.
        </P>
      </Section>

      <Section title="13. Indemnification">
        <P>
          You agree to indemnify and hold harmless {COMPANY} from any claims, damages, losses,
          or expenses (including reasonable legal fees) arising out of your use of the App,
          your violation of these Terms, or your violation of any third party's rights.
        </P>
      </Section>

      <Section title="14. Termination">
        <P>
          We may suspend or terminate your access to the App at any time, with or without cause,
          with or without notice. You may stop using the App at any time. Upon termination,
          your license to use the App ends immediately. Sections 8, 11, 12, 13, and 16 survive
          termination.
        </P>
      </Section>

      <Section title="15. Changes to These Terms">
        <P>
          We may update these Terms from time to time. If we make material changes, we will
          notify you via the App or by email at least 7 days before they take effect. Continued
          use of the App after the effective date constitutes acceptance of the revised Terms.
        </P>
      </Section>

      <Section title="16. Governing Law & Disputes">
        <P>
          These Terms are governed by the laws of the State of Delaware, United States, without
          regard to conflict of law principles. Any dispute arising out of these Terms shall be
          resolved by binding arbitration administered by the American Arbitration Association
          under its Consumer Arbitration Rules, except that either party may seek injunctive
          relief in a court of competent jurisdiction.
        </P>
        <P>
          YOU AGREE TO WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR
          CLASS-WIDE ARBITRATION.
        </P>
      </Section>

      <Section title="17. Contact">
        <P>
          Questions about these Terms? Email{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "#B8860B" }}>
            {CONTACT_EMAIL}
          </a>
          .
        </P>
        <P>{COMPANY}</P>
      </Section>
    </LegalLayout>
  );
}
